# Generated by Django 4.1 on 2022-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('abstract', models.CharField(max_length=2500)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
