# Generated by Django 4.1 on 2022-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0002_tcc_advisor_tcc_author_tcc_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='tcc',
            name='keywords',
            field=models.ManyToManyField(to='tcc.keyword'),
        ),
    ]
